development:
  adapter: postgresql
  encoding: utf8
  database: luke
  pool: 5
  host: localhost
  username: postgres
  password: 123456

production:
  adapter: postgresql
  encoding: utf8
  database: luke_production
  pool: 5
  host: localhost
  username: sjyyt
  password: iamtmx203